spring.application.name=EmployeeManagement
spring.datasource.url=jdbc:mysql://localhost:3306/Employee_Management_System
spring.datasource.username=root
spring.datasource.password=8797

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
spring.output.ansi.enabled=always


#logging.level.root=TRACE
#spring.jpa.open-in-view=false
#logging.level.com.classes=TRACE
